### ISSUE TITLE
Some files from  academictorrents are broken

### ISSUE THREAD

**Issue by kkulczak** [philipperemy/timit#4]
Some .wav fiels are broken.
`sph2pipe` from kaldi complain that those file are not in SPHERE format.

```
TIMIT/TEST/DR1/FAKS0/SA1.WAV
TIMIT/TEST/DR1/FAKS0/SA2.WAV
TIMIT/TEST/DR1/FAKS0/SI1573.WAV
TIMIT/TEST/DR1/FAKS0/SI2203.WAV
TIMIT/TRAIN/DR4/MPRT0/SI1210.WAV
TIMIT/TRAIN/DR4/MPRT0/SX40.WAV

**Comment by philipperemy** [comment]
Oh wow. Maybe try to re-download it. Did you have enough space on your hard drive? I don't think the torrent or the content changed recently.

If it still does not work, you can use the second link: https://www.kaggle.com/mfekadu/darpa-timit-acousticphonetic-continuous-speech

Let me know how you solved the problem!
